[package]
name = "runner_crate"
version = "0.1.0"
edition = "2024_07"

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

# Core Starknet dependencies
[dependencies]
starknet = "2.12.0"

[dev-dependencies]
snforge_std = "0.47.0"
assert_macros = "2.11.4"

# Starknet contract compilation target
