name: starklings StarkSharks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        override: true

    - name: Build and Run Starklings
      run: |
        git clone https://github.com/StarkSharks/starklings-cairo1.git
        cd starklings-cairo1
        cargo run -r --bin starklings
